#!/bin/bash

# Never touch:

# com.android.systemui (The entire user interface)
# com.android.settings (Settings menu)
# com.google.android.ims (Essential for VoLTE, Wi-Fi Calling, and texting)
# com.shannon.imsservice (Essential for VoLTE, Wi-Fi Calling, and texting)
# com.google.android.as (Android System Intelligence (powers Live Caption, Now Playing, and smart replies).
# com.google.android.gms ( Google Play Services. Almost nothing works without this.
# com.google.android.gsf (Google Services Framework)
# com.android.phone (Dialing and signals)
# com.sec.phone (Dialing and signals)
# com.google.android.gms (Google Play Services)
# com.google.android.networkstack (Internet connectivity)
# com.android.bookmarkprovider
# com.android.cellbroadcastreceiver
# com.android.cellbroadcastreceiver.overlay.common
# com.android.printspooler
# com.android.statementservice
# com.google.android.biometrics.setupwizard (biometrics setup)
# com.google.android.settings.biometrics.face.settings (for Face Unlock)
# com.google.hardware.pixel.biometrics.fingerprint(for Fingerprint Unlock)
# com.samsung.android.biometrics.app.setting (Fingerprint/Face unlock)

LOGFILE="debloat.log"
rm "$LOGFILE" &> /dev/null
touch "$LOGFILE"

# 1. Check if adb is installed/in the PATH
if ! command -v adb &> /dev/null; then
    echo "Error: adb is not installed or not in your PATH."
    exit 1
else
    echo "adb is installed."
fi

# 2. Check for attached devices
# We filter for 'device$' to ensure it's fully connected and authorized
# 'unauthorized' or 'offline' states will be ignored.
DEVICE_COUNT=$(adb devices | grep -v "List of devices" | grep "device$" | wc -l)

if [ "$DEVICE_COUNT" -eq 0 ]; then
    echo "Error: No authorized Android devices found."
    echo "Check your USB cable and ensure 'USB Debugging' is enabled/authorized."
    exit 1
elif [ "$DEVICE_COUNT" -gt 1 ]; then
    echo "Multiple devices ($DEVICE_COUNT) detected. You may need to specify -s <serial>."
    exit 1
else
    echo "Android device is attached and ready."
fi

# Detect Current Launcher
CURRENT_LAUNCHER=$(adb shell cmd shortcut get-default-launcher 2>&1 | awk -F'/' '{print $1}')
{
    echo "------------------------------------------------"
    echo "Model:           $(adb shell getprop ro.product.model)"
    echo "Android Version: $(adb shell getprop ro.build.version.release)"
    echo "Current Date:    $(adb shell date)"
    echo "Launcher:        $CURRENT_LAUNCHER"
    echo "------------------------------------------------"
} | tee -a "$LOGFILE"

if [[ "$CURRENT_LAUNCHER" == *"bitpit.launcher"* ]]; then
    SAFE_TO_DISABLE_GOOGLE=true
elif [[ "$CURRENT_LAUNCHER" == *"com.teslacoilsw.launcher"* ]]; then
    SAFE_TO_DISABLE_GOOGLE=true
else
    SAFE_TO_DISABLE_GOOGLE=false
fi

echo "" >> "$LOGFILE"
echo "Installed packages before debloat:" >> "$LOGFILE"
echo "" >> "$LOGFILE"
adb shell cmd package list packages >> "$LOGFILE"

echo "" >> "$LOGFILE"
echo "Disabled packages before debloat:" >> "$LOGFILE"
echo "" >> "$LOGFILE"
adb shell cmd package list packages -d >> "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Google Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.google.android.retaildemo ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0  &  2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.apps.retaildemo.preload ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.retaildemo.preload 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.google.android.apps.dreamliner" 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.dreamliner 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.apps.pixel.familyspace" 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.pixel.familyspace 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.apps.internal.betterbug" 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.internal.betterbug 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.hotwordenrollment.okgoogle ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.hotwordenrollment.okgoogle 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.hotwordenrollment.xgoogle ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.hotwordenrollment.xgoogle 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.providers.partnerbookmarks ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.providers.partnerbookmarks 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.wallpaper.livepicker ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.wallpaper.livepicker 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.customermobile.preload.vzw ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.customermobile.preload.vzw 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.apps.tips ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.tips 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.apps.wellbeing ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.wellbeing 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.feedback ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.feedback 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.printservice.recommendation ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.printservice.recommendation 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.pixel.livewallpaper ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.pixel.livewallpaper 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.pixel.dynamicwallpapers ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.pixel.dynamicwallpapers 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.verizon.llkagent ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.verizon.llkagent 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.verizon.mips.services ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.verizon.mips.services 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.verizon.services ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.verizon.services 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.samsung.android.widget.pictureframe ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.widget.pictureframe 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.app.telephonyui.esimclient ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.app.telephonyui.esimclient 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.app.sharelive ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.app.sharelive 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.themestore ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.themestore 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sec.android.app.popupcalculator ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sec.android.app.popupcalculator 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.wallpaper.live ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.wallpaper.live 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.sdk.handwriting ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.sdk.handwriting 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.video ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.video 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.audiomirroring ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.audiomirroring 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.app.watchmanagerstub ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.app.watchmanagerstub 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.app.soundpicker ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.app.soundpicker 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.app.dressroom ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.app.dressroom 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.stickercenter ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.stickercenter 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.aremoji ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.aremoji 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.forest ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.forest 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.mapsagent ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.mapsagent 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.storyservice ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.storyservice 2>&1 | tee -a "$LOGFILE"


echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling MIUI Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.mi.android.globallauncher ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.mi.android.globallauncher 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.mi.android.globalpersonalassistant ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.mi.android.globalpersonalassistant 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.mi.globalTrendNews ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.mi.globalTrendNews 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.mi.health ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.mi.health 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.mi.webkit.core ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.mi.webkit.core 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.mipay.wallet.id ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.mipay.wallet.id 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.mipay.wallet.in ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.mipay.wallet.in 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.analytics ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.analytics 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.android.fashiongallery ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.android.fashiongallery 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.aod ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.aod 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.bugreport ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.bugreport 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.calculator ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.calculator 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.cleanmaster ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.cleanmaster 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.compass ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.compass 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.fm ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.fm 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.fmservice ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.fmservice 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.hybrid ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.hybrid 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.hybrid.accessory ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.hybrid.accessory 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.micloudsync ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.micloudsync 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.mishare.connectivity ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.mishare.connectivity 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.msa.global ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.msa.global 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.notes ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.notes 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.phrase ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.phrase 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.screenrecorder ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.screenrecorder 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.smsextra ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.smsextra 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.system ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.system 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.systemui.carriers.overlay ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.systemui.carriers.overlay 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.touchassistant ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.touchassistant 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.translation.kingsoft ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.translation.kingsoft 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.userguide ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.userguide 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.videoplayer ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.videoplayer 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.weather2 ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.weather2 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.yellowpage ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.yellowpage 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Xiaomi Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.sohu.inputmethod.sogou.xiaomi ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sohu.inputmethod.sogou.xiaomi 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.calendar ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.calendar 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.glgm ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.glgm 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.joyose ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.joyose 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.micloud.sdk ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.micloud.sdk 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.midrop ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.midrop 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.mipicks ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.mipicks 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.miplay_client ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.miplay_client 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.mircs ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.mircs 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.payment ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.payment 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.scanner ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.scanner 2>&1 | tee -a "$LOGFILE"
echo "uninstalling cn.wps.xiaomi.abroad.lite ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 cn.wps.xiaomi.abroad.lite 2>&1 | tee -a "$LOGFILE"
echo "uninstalling android.autoinstalls.config.Xiaomi.model ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 android.autoinstalls.config.Xiaomi.model 2>&1 | tee -a "$LOGFILE"
echo "uninstalling android.qvaoverlay.common ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 android.qvaoverlay.common 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.contacts ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.contacts 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.incallui ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.incallui 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.inputsettings.overlay.miui ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.inputsettings.overlay.miui 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.providers.partnerbookmarks ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.providers.partnerbookmarks 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.apps.turbo ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.turbo 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.apps.youtube.music ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.youtube.music 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.cellbroadcastreceiver.overlay.miui ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.cellbroadcastreceiver.overlay.miui 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.cellbroadcastservice.overlay.miui ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.cellbroadcastservice.overlay.miui 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.printservice.recommendation ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.printservice.recommendation 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.videos ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.videos 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.mi.globalbrowser ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.mi.globalbrowser 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.mi.globalminusscreen ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.mi.globalminusscreen 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.analytics ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.analytics 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.daemon ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.daemon 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.miservice ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.miservice 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.msa.global ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.msa.global 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.phone.carriers.overlay.vodafone ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.phone.carriers.overlay.vodafone 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.player ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.player 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.settings.rro.device.hide.statusbar.overlay ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.settings.rro.device.hide.statusbar.overlay 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.settings.rro.device.type.overlay ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.settings.rro.device.type.overlay 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.videoplayer ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.videoplayer 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.miui.yellowpage ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.miui.yellowpage 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.qti.dcf ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.qti.dcf 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.tencent.soter.soterserver ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.tencent.soter.soterserver 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.barrage ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.barrage 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.payment ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.payment 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.xiaomi.simactivate.service ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.xiaomi.simactivate.service 2>&1 | tee -a "$LOGFILE"
echo "uninstalling org.ifaa.aidl.manager ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 org.ifaa.aidl.manager 2>&1 | tee -a "$LOGFILE"


echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Huawei Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.android.mediacenter ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.mediacenter 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.android.UEInfoCheck ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.android.UEInfoCheck 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.android.chr ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.android.chr 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.intelligent ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.intelligent 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.appmarket ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.appmarket 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.parentcontrol ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.parentcontrol 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.iflytek.speechsuite ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.iflytek.speechsuite 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.wallet ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.wallet 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.phoneservice ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.phoneservice 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.android.findmyphone ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.android.findmyphone 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.baidu.input_huawei ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.baidu.input_huawei 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.marvin.talkback ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.marvin.talkback 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.hwid ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.hwid 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.vassistant ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.vassistant 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.watch.sync ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.watch.sync 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.inputmethod.latin ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.inputmethod.latin 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.hiboard ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.hiboard 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.skytone ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.skytone 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.android.hwpay ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.android.hwpay 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.dreams.phototable ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.dreams.phototable 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.intelligent ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.intelligent 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.videoeditor ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.videoeditor 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.browser ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.browser 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.trustagent ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.trustagent 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.trustspace ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.trustspace 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.apps.tag ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.apps.tag 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.hwvplayer.youku ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.hwvplayer.youku 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.android.dreams.basic ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.android.dreams.basic 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.example.android.notepad ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.example.android.notepad 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.android.AutoRegSms ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.android.AutoRegSms 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.himovie ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.himovie 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.huawei.browser ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.huawei.browser 2>&1 | tee -a "$LOGFILE"

# 
echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling ANT+ Service Apps" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling dsi.ant.sample.acquirechannels ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 dsi.ant.sample.acquirechannels 2>&1 | tee -a "$LOGFILE"
echo "uninstalling dsi.ant.service.socket ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 dsi.ant.service.socket 2>&1 | tee -a "$LOGFILE"
echo "uninstalling dsi.ant.plugins.antplus ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 dsi.ant.plugins.antplus 2>&1 | tee -a "$LOGFILE"


echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Samsung Bixby Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling samsung.android.bixby.wakeup ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.bixby.wakeup 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.app.spage ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.app.spage 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.app.routines ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.app.routines 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.bixby.service ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.bixby.service 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.visionintelligence ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.visionintelligence 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.bixby.agent ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.bixby.agent 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.bixby.agent.dummy ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.bixby.agent.dummy 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.bixbyvision.framework ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.bixbyvision.framework 2>&1 | tee -a "$LOGFILE"


echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Samsung General System Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"


echo "uninstalling samsung.android.messaging ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.messaging 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.easyonehand ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.easyonehand 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.drivelink.stub ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.drivelink.stub 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.widgetapp.samsungapps ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.widgetapp.samsungapps 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.app.sbrowser ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.app.sbrowser 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.mateagent ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.mateagent 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.easyMover.Agent ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.easyMover.Agent 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.app.watchmanagerstub ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.app.watchmanagerstub 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.daemonapp ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.daemonapp 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.app.social ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.app.social 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.ecomm.global ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.ecomm.global 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.app.voicenote ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.app.voicenote 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.oneconnect ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.oneconnect 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.voc ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.voc 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.app.popupcalculator ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.app.popupcalculator 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.splitsound ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.splitsound 2>&1 | tee -a "$LOGFILE"
echo "uninstalling mobeam.barcodeService ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 mobeam.barcodeService 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.app.dressroom ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.app.dressroom 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.scloud ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.scloud 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.sdk.handwriting ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.sdk.handwriting 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.sdk.professionalaudio.utility.jammonitor ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.sdk.professionalaudio.utility.jammonitor 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.universalswitch ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.universalswitch 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.visioncloudagent ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.visioncloudagent 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.visionintelligence ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.visionintelligence 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.widgetapp.yahooedge.finance ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.widgetapp.yahooedge.finance 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.widgetapp.yahooedge.sport ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.widgetapp.yahooedge.sport 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.app.highlightplayer ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.app.highlightplayer 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.safetyinformation ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.safetyinformation 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.storyservice ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.storyservice 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.service.aircommand ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.service.aircommand 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.app.aodservice ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.app.aodservice 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.app.dexonpc ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.app.dexonpc 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.ardrawing ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.ardrawing 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.svoiceime ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.svoiceime 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.beaconmanager ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.beaconmanager 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.email.provider ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.email.provider 2>&1 | tee -a "$LOGFILE"
echo "uninstalling wsomacp ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 wsomacp 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.app.sharelive ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.app.sharelive 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sec.android.app.samsungapps ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sec.android.app.samsungapps 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.themestore ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.themestore 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.apps.tachyon ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.tachyon 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.apps.bard ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.bard 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.youtube ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.youtube 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.hiya.star ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.hiya.star 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sec.android.app.kidshome ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sec.android.app.kidshome 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.kidsinstaller ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.kidsinstaller 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.app.parentalcare ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.app.parentalcare 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.spay ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.spay 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.google.android.apps.messaging ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.google.android.apps.messaging 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sec.android.app.popupcalculator ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sec.android.app.popupcalculator 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.app.notes ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.app.notes 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.android.app.reminder ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.android.app.reminder 2>&1 | tee -a "$LOGFILE"

# Samsung Pay and Pass
echo "uninstalling samsung.android.samsungpassautofill ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.samsungpassautofill 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.authfw ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.authfw 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.samsungpass ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.samsungpass 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.spay ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.spay 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.spayfw ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.spayfw 2>&1 | tee -a "$LOGFILE"

# Samsung Printing Service Components
echo "uninstalling android.bips ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 android.bips 2>&1 | tee -a "$LOGFILE"
echo "uninstalling google.android.printservice.recommendation ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 google.android.printservice.recommendation 2>&1 | tee -a "$LOGFILE"
echo "uninstalling android.printspooler ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 android.printspooler 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Samsung Recreational Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling boxer.app ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 boxer.app 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.wellbeing ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.wellbeing 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.da.daagent ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.da.daagent 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.service.livedrawing ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.service.livedrawing 2>&1 | tee -a "$LOGFILE"

# Samsung AR Emoji
echo "uninstalling samsung.android.aremoji ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.aremoji 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.mimage.avatarstickers ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.mimage.avatarstickers 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.emojiupdater ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.emojiupdater 2>&1 | tee -a "$LOGFILE"

# Samsung Gear VR
echo "uninstalling samsung.android.hmt.vrsvc ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.hmt.vrsvc 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.app.vrsetupwizardstub ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.app.vrsetupwizardstub 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.hmt.vrshell ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.hmt.vrshell 2>&1 | tee -a "$LOGFILE"
echo "uninstalling google.vr.vrcore ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 google.vr.vrcore 2>&1 | tee -a "$LOGFILE"

# Samsung Kids Mode
echo "uninstalling samsung.android.kidsinstaller ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.kidsinstaller 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.app.camera.sticker.facearavatar.preload ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.app.camera.sticker.facearavatar.preload 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.app.kidshome ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.app.kidshome 2>&1 | tee -a "$LOGFILE"

# Samsung Game Launcher and Settings
echo "uninstalling samsung.android.game.gamehome ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.game.gamehome 2>&1 | tee -a "$LOGFILE"
echo "uninstalling enhance.gameservice ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 enhance.gameservice 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.game.gametools ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.game.gametools 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.game.gos ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.game.gos 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.android.gametuner.thin ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.gametuner.thin 2>&1 | tee -a "$LOGFILE"

# Samsung LED Cover
echo "uninstalling samsung.android.app.ledbackcover ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.android.app.ledbackcover 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.cover.ledcover ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.cover.ledcover 2>&1 | tee -a "$LOGFILE"

# Samsung Dex
echo "uninstalling sec.android.desktopmode.uiservice ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.desktopmode.uiservice 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.desktopsystemui ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.desktopsystemui 2>&1 | tee -a "$LOGFILE"
echo "uninstalling sec.android.app.desktoplauncher ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 sec.android.app.desktoplauncher 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Samsung Verizon Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling vcast.mediamanager ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 vcast.mediamanager 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.vmmhux ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.vmmhux 2>&1 | tee -a "$LOGFILE"
echo "uninstalling vzw.hss.myverizon ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 vzw.hss.myverizon 2>&1 | tee -a "$LOGFILE"
echo "uninstalling asurion.android.verizon.vms ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 asurion.android.verizon.vms 2>&1 | tee -a "$LOGFILE"
echo "uninstalling motricity.verizon.ssodownloadable ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 motricity.verizon.ssodownloadable 2>&1 | tee -a "$LOGFILE"
echo "uninstalling vzw.hs.android.modlite ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 vzw.hs.android.modlite 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.vvm ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.vvm 2>&1 | tee -a "$LOGFILE"
echo "uninstalling vznavigator.[You_Model_Here] ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 vznavigator.[You_Model_Here] 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling AT&T Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling att.dh ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 att.dh 2>&1 | tee -a "$LOGFILE"
echo "uninstalling att.dtv.shaderemote ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 att.dtv.shaderemote 2>&1 | tee -a "$LOGFILE"
echo "uninstalling att.tv ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 att.tv 2>&1 | tee -a "$LOGFILE"
echo "uninstalling samsung.attvvm ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 samsung.attvvm 2>&1 | tee -a "$LOGFILE"
echo "uninstalling att.myWireless ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 att.myWireless 2>&1 | tee -a "$LOGFILE"
echo "uninstalling asurion.android.protech.att ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 asurion.android.protech.att 2>&1 | tee -a "$LOGFILE"
echo "uninstalling att.android.attsmartwifi ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 att.android.attsmartwifi 2>&1 | tee -a "$LOGFILE"


echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Motorola Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.motorola.motocare ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.motorola.motocare 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.motorola.ccc.notification ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.motorola.ccc.notification 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.motorola.dimo ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.motorola.dimo 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.motorola.moto ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.motorola.moto 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.motorola.spaces ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.motorola.spaces 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.motorola.aiservices ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.motorola.aiservices 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.inmobi.weather ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.inmobi.weather 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.motorola.securityhub ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.motorola.securityhub 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.motorola.brapps ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.motorola.brapps 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.motorola.gamemode ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.motorola.gamemode 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Sony Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.sonymobile.moviecreator ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sonymobile.moviecreator 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sonymobile.cinemapro ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sonymobile.cinemapro 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sonymobile.android.externalkeyboardjp ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sonymobile.android.externalkeyboardjp 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sonymobile.dropbox.system ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sonymobile.dropbox.system 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sonymobile.pip ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sonymobile.pip 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sonymobile.onehand ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sonymobile.onehand 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sonymobile.dualshockmanager ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sonymobile.dualshockmanager 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sonymobile.support ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sonymobile.support 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.sonymobile.retaildemo ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.sonymobile.retaildemo 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Microsoft Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.microsoft.skydrive ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.microsoft.skydrive 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.skype.raider ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.skype.raider 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.microsoft.office.excel ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.microsoft.office.excel 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.microsoft.office.word ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.microsoft.office.word 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.microsoft.office.powerpoint ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.microsoft.office.powerpoint 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Verizon Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.vcast.mediamanager ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.vcast.mediamanager 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.vmmhux ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.vmmhux 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.vzw.hss.myverizon ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.vzw.hss.myverizon 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.asurion.android.verizon.vms ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.asurion.android.verizon.vms 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.motricity.verizon.ssodownloadable ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.motricity.verizon.ssodownloadable 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.vzw.hs.android.modlite ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.vzw.hs.android.modlite 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.samsung.vvm ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.samsung.vvm 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.vznavigator.[You_Model_Here] ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.vznavigator.[You_Model_Here] 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling T-Mobile Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.mobitv.client.tmobiletvhd ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.mobitv.client.tmobiletvhd 2>&1 | tee -a "$LOGFILE"
echo "uninstalling us.com.dt.iq.appsource.tmobile ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 us.com.dt.iq.appsource.tmobile 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Facebook Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.facebook.services ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.facebook.services 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.facebook.system ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.facebook.system 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.facebook.katana ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.facebook.katana 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.facebook.system ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.facebook.system 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.facebook.appmanager ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.facebook.appmanager 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.facebook.services ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.facebook.services 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Amazon Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.amazon.mShop.android ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.amazon.mShop.android 2>&1 | tee -a "$LOGFILE"
echo "uninstalling in.amazon.mShop.android.shopping ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 in.amazon.mShop.android.shopping 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.amazon.fv ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.amazon.fv 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.amazon.kindle ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.amazon.kindle 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.amazon.mp3 ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.amazon.mp3 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.amazon.venezia ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.amazon.venezia 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.bsp.catchlog ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.bsp.catchlog 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.amazon.appmanager ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.amazon.appmanager 2>&1 | tee -a "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Netflix Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.netflix.partner.activation ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.netflix.partner.activation 2>&1 | tee -a "$LOGFILE"
#echo "uninstalling com.netflix.mediaclient ..."
#adb shell pm uninstall -k --user 0 com.netflix.mediaclient

echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Opera Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"

echo "uninstalling com.opera.app.news ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.opera.app.news 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.opera.branding ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.opera.branding 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.opera.branding.news ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.opera.branding.news 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.opera.mini.native ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.opera.mini.native 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.opera.preinstall ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.opera.preinstall 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.tencent.soter.soterserver ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.tencent.soter.soterserver 2>&1 | tee -a "$LOGFILE"


echo "" 2>&1 | tee -a "$LOGFILE"
echo "Uninstalling Miscellaneous Bloatware" 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"
echo "uninstalling flipboard.boxer.app ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 flipboard.boxer.app 2>&1 | tee -a "$LOGFILE"
echo "uninstalling flipboard.app ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 flipboard.app 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.hancom.office.editor.hidden ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.hancom.office.editor.hidden 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.audible.application ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.audible.application 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.blurb.checkout ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.blurb.checkout 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.cequint.ecid ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.cequint.ecid 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.imdb.mobile ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.imdb.mobile 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.gotv.nflgamecenter.us.lite ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.gotv.nflgamecenter.us.lite 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.infraware.polarisoffice5 ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.infraware.polarisoffice5 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.nuance.swype.input ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.nuance.swype.input 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.autonavi.minimap ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.autonavi.minimap 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.caf.fmradio ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.caf.fmradio 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.duokan.phone.remotecontroller ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.duokan.phone.remotecontroller 2>&1 | tee -a "$LOGFILE"
echo "uninstalling org.simalliance.openmobileapi.service ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 org.simalliance.openmobileapi.service 2>&1 | tee -a "$LOGFILE"
echo "uninstalling com.duokan.phone.remotecontroller.peel.plugin ..." 2>&1 | tee -a "$LOGFILE"
adb shell pm uninstall -k --user 0 com.duokan.phone.remotecontroller.peel.plugin 2>&1 | tee -a "$LOGFILE"

# --- Interactive AI Disabling Section ---

echo "" 2>&1 | tee -a "$LOGFILE"
read -p "Disable AI (Gemini) but keep local voice typing? [y/N]: " confirm_degemini

if [[ "$confirm_degemini" =~ ^[Yy]$ ]]; then
    echo "Disabling Gemini & Heavy AI (Voice-to-Text Safe)..." 2>&1 | tee -a "$LOGFILE"

    # We DO NOT clear com.google.android.as to keep voice models
    
    # Disable the LLM engine (Gemini Nano)
    echo "Disabling com.google.android.aicore" 2>&1 | tee -a "$LOGFILE"
    adb shell pm disable-user --user 0 com.google.android.aicore 2>&1 | tee -a "$LOGFILE"

# Is now integrated into the Google App
#     # Disable the Gemini App specifically
#     echo "Disabling com.google.apps.googleassistant"
#     adb shell pm disable-user --user 0 com.google.android.apps.googleassistant

    # Disable AI Wallpapers
    echo "Disabling com.google.apps.aiwallpapers" 2>&1 | tee -a "$LOGFILE"
    adb shell pm disable-user --user 0 com.google.android.apps.aiwallpapers 2>&1 | tee -a "$LOGFILE"

	echo "" 2>&1 | tee -a "$LOGFILE"
    echo "Gemini suppressed. Local Voice-to-Text remains functional." 2>&1 | tee -a "$LOGFILE"
fi

echo "" 2>&1 | tee -a "$LOGFILE"
read -p "Disable ALL AI features (Gemini, Assistant, AI Core)? [y/N]: " confirm_deai

if [[ "$confirm_deai" =~ ^[Yy]$ ]]; then
	echo "" 2>&1 | tee -a "$LOGFILE"
    echo "Disabling AI components..." 2>&1 | tee -a "$LOGFILE"

    # Clear learning data/caches
    echo "Clearing device learning com.google.android.as" 2>&1 | tee -a "$LOGFILE"
    adb shell pm clear com.google.android.as 2>&1 | tee -a "$LOGFILE"
    echo "Clearing search cache com.google.android." 2>&1 | tee -a "$LOGFILE"
    adb shell pm clear com.google.android.googlequicksearchbox 2>&1 | tee -a "$LOGFILE"

    # Disable AI Engine and Generative features
    echo "Disabling com.google.android.aicore" 2>&1 | tee -a "$LOGFILE"
    adb shell pm disable-user --user 0 com.google.android.aicore 2>&1 | tee -a "$LOGFILE"
    echo "Disabling com.google.android.apps.aiwallpapers" 2>&1 | tee -a "$LOGFILE"
    adb shell pm disable-user --user 0 com.google.android.apps.aiwallpapers 2>&1 | tee -a "$LOGFILE"

    # Disable Assistant & Gemini stubs
    echo "Disabling com.google.android.apps.googleassistant" 2>&1 | tee -a "$LOGFILE"
    adb shell pm disable-user --user 0 com.google.android.apps.googleassistant 2>&1 | tee -a "$LOGFILE"
    echo "Disabling com.google.android.googlequicksearchbox.nga_resources" 2>&1 | tee -a "$LOGFILE"
    adb shell pm disable-user --user 0 com.google.android.googlequicksearchbox.nga_resources 2>&1 | tee -a "$LOGFILE"

    # Disable Personalization
    echo "Disabling com.google.android.ondevicepersonalization.services" 2>&1 | tee -a "$LOGFILE"
    adb shell pm disable-user --user 0 com.google.android.ondevicepersonalization.services 2>&1 | tee -a "$LOGFILE"

	echo "" 2>&1 | tee -a "$LOGFILE"
    echo "All AI features have been suppressed." 2>&1 | tee -a "$LOGFILE"
fi

# --- Interactive Google App Disabling Section ---

echo ""
if [ "$SAFE_TO_DISABLE_GOOGLE" = true ]; then
    read -p "You are using an alternative launcher. Disable the main Google App (Search/Discover)? [y/N]: " confirm_degoogle
    if [[ "$confirm_degoogle" =~ ^[Yy]$ ]]; then
        echo "Disabling Google Search App..." 2>&1 | tee -a "$LOGFILE"
        adb shell pm disable-user --user 0 com.google.android.googlequicksearchbox 2>&1 | tee -a "$LOGFILE"
        echo "Google App disabled." 2>&1 | tee -a "$LOGFILE"
    else
        adb shell pm disable-user --user 0 com.google.android.googlequicksearchbox.nga_resources 2>&1 | tee -a "$LOGFILE"
        echo "Assistant UI silenced (Google App kept active)." 2>&1 | tee -a "$LOGFILE"
    fi
else
    echo "Skipping Google App disable: Standard Pixel Launcher requires it." 2>&1 | tee -a "$LOGFILE"
    # Just silence the assistant UI anyway
    echo "Disabling com.google.android.googlequicksearchbox.nga_resources" 2>&1 | tee -a "$LOGFILE"
    adb shell pm disable-user --user 0 com.google.android.googlequicksearchbox.nga_resources 2>&1 | tee -a "$LOGFILE"
fi

echo "" >> "$LOGFILE"
echo "Installed packages after debloat:" >> "$LOGFILE"
echo "" >> "$LOGFILE"
adb shell cmd package list packages >> "$LOGFILE"

echo "" >> "$LOGFILE"
echo "Disabled packages after debloat:" >> "$LOGFILE"
echo "" >> "$LOGFILE"
adb shell cmd package list packages -d >> "$LOGFILE"

echo "" 2>&1 | tee -a "$LOGFILE"
echo "De-bloat complete." 2>&1 | tee -a "$LOGFILE"
echo "" 2>&1 | tee -a "$LOGFILE"
